### ISSUE TITLE
配置求助，配置完评论返回错误信息

### ISSUE THREAD

**Issue by HeLongaa** [soxft/waline-async-mail#3]
invalid json response body at https://test.duolaa.asia/ reason: Unexpected token < in JSON at position 0

**Comment by soxft** [comment]
https://test.duolaa.asia/  这是您部署完成之后的网址么，似乎反响代理没有配置好？ 直接访问报502

**Comment by HeLongaa** [comment]
哇，发现了，是端口搞错了，服务是正常的，感谢回复
